version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: bot_db
    environment:
      POSTGRES_DB: DB_NAME
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: weather_bot
    environment:
      DB_HOST: db
      DB_NAME: DB_NAME
      DB_USER: DB_USER
      DB_PASSWORD: DB_PASSWORD
      TELEGRAM_TOKEN: TELEGRAM_TOKEN
      API_URL: "https://api.weatherapi.com/v1"
      API_KEY: "TELEGRAM_TOKEN"
    depends_on:
      - db
    ports:
      - "8081:8080"

volumes:
  postgres_data:

